# Generated by Django 3.0.3 on 2020-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='gambar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='jenis',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
