# Generated by Django 3.0.3 on 2020-04-18 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0002_auto_20200418_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='CssTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=50, null=True)),
                ('col', models.CharField(max_length=50, null=True)),
                ('block', models.CharField(max_length=50, null=True)),
                ('blockhov', models.CharField(max_length=50, null=True)),
                ('quickview', models.CharField(max_length=50, null=True)),
                ('blocktext', models.CharField(max_length=50, null=True)),
                ('detail_link', models.CharField(max_length=50, null=True)),
                ('stext104', models.CharField(max_length=50, null=True)),
                ('stext105', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
