# Generated by Django 3.0.3 on 2020-04-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0004_auto_20200418_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csstags',
            name='block',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='blockhov',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='blocktext',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='blocktextchild1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='blocktextchild2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='btn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='col',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='detail_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='icon1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='icon1img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='icon2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='icon2img',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='quickview',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='row',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='stext104',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csstags',
            name='stext105',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
