# Generated by Django 3.0.3 on 2020-04-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0008_auto_20200418_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CssTags',
        ),
    ]
