# Generated by Django 3.0.3 on 2020-04-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0009_delete_csstags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], default='S', max_length=50),
        ),
    ]
