# Generated by Django 3.0.3 on 2020-04-19 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0010_auto_20200418_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemesanan',
            name='barang',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pemesanan.Barang'),
        ),
        migrations.AlterField(
            model_name='pemesanan',
            name='color',
            field=models.CharField(choices=[('RED', 'RED'), ('BLUE', 'BLUE'), ('WHITE', 'WHITE'), ('GREY', 'GREY')], default='RED', max_length=50),
        ),
    ]
