# Generated by Django 3.0.3 on 2020-04-20 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0015_auto_20200420_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='barang',
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='barang_key',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='pemesanan.Barang'),
        ),
    ]
