# Generated by Django 3.0.3 on 2020-04-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemesanan', '0017_auto_20200420_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pemesanan',
            name='barang_key',
        ),
        migrations.AddField(
            model_name='pemesanan',
            name='barang',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='pemesanan.Barang'),
        ),
    ]
